on: [push, pull_request]

name: commit checks

jobs:

  # TODO: Add the FreeBSD back, but currently support of it in `cross` is broken

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - stable
          - 1.31.0  # MSRV
        arch:
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
      steps:
        - uses: actions/checkout@master
        - uses: actions-rs/toolchain@master
          with:
            toolchain: ${{ matrix.toolchain }}
            target: ${{ matrix.arch }}
            override: true

        - name: build
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: build
            args: --target ${{ matrix.arch }}

        - name: test
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: test
            args: --target ${{ matrix.arch }}

        - name: clippy
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: clippy
            args: --target ${{ matrix.arch }} -- -D warnings

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - stable
          - 1.31.0  # MSRV
        arch:
          - i686-pc-windows-msvc
          - x86_64-pc-windows-msvc
      steps:
        - uses: actions/checkout@master
        - uses: actions-rs/toolchain@master
          with:
            toolchain: ${{ matrix.toolchain }}
            target: ${{ matrix.arch }}
            override: true

        - name: build
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: build
            args: --target ${{ matrix.arch }}

        - name: test
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: test
            args: --target ${{ matrix.arch }}

        - name: clippy
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: clippy
            args: --target ${{ matrix.arch }} -- -D warnings

  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - stable
          - 1.31.0  # MSRV
        arch:
          - i686-apple-darwin
          - x86_64-apple-darwin
      steps:
        - uses: actions/checkout@master
        - uses: actions-rs/toolchain@master
          with:
            toolchain: ${{ matrix.toolchain }}
            target: ${{ matrix.arch }}
            override: true

        - name: build
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: build
            args: --target ${{ matrix.arch }}

        - name: test
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: test
            args: --target ${{ matrix.arch }}

        - name: clippy
          uses: actions-rs/cargo@master
          with:
            use-cross: true
            command: clippy
            args: --target ${{ matrix.arch }} -- -D warnings
