on: [push, pull_request]

name: commit checks

jobs:
  build:
    strategy:
      matrix:
        arch:
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - i686-apple-darwin
          - x86_64-apple-darwin
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu
          - i686-unknown-freebsd
          - x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@master
        with:
          use-cross: true
          command: build
          args: --target '${{ matrix.arch }}'
      - uses: actions-rs/cargo@master
        with:
          use-cross: true
          command: test
          args: --target '${{ matrix.arch }}'
        # Cross does not support testing for FreeBSD
        if: !(matrix.arch.contains('freebsd'))

      - uses: actions-rs/cargo@master
        with:
          use-cross: true
          command: clippy
          args: -target ${{ matrix.arch }} -- -D warnings
