on: [push, pull_request]

name: commit checks

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:

        os:
          - ubuntu-latest
          - macOS-latest
        toolchain:
          - stable
          - 1.31.0  # MSRV
        arch:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-unknown-freebsd
          - x86_64-apple-darwin

        # Since matrix does not allow to include totally new jobs,
        # we are required to drop old one
        exclude:
          - os: ubuntu-latest
            arch: x86_64-apple-darwin
          - os: macOS-latest
            arch: x86_64-unknown-linux-gnu
          - os: macOS-latest
            arch: x86_64-pc-windows-gnu
          - os: macOS-latest
            arch: x86_64-unknown-freebsd

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@dev
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.arch }}
          override: true

      - name: build
        uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.arch }}

      - name: test
        # Not supported by cross yet
        if: contains(matrix.arch, 'freebsd') == false
        uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.arch }}

      - name: clippy
        uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: clippy
          args: --target ${{ matrix.arch }} -- -D warnings
