on: [push, pull_request]

name: commit checks

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - i686-apple-darwin
          - x86_64-apple-darwin
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu
          - i686-unknown-freebsd
          - x86_64-unknown-freebsd
        toolchain:
            - stable
            - 1.31.0  # MSRV

    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: build
          toolchain: ${{ matrix.toolchain }}
          args: --target ${{ matrix.arch }}

      - uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: test
          toolchain: ${{ matrix.toolchain }}
          args: --target ${{ matrix.arch }}

      - uses: actions-rs/cargo@cross-dev
        with:
          use-cross: true
          command: clippy
          toolchain: ${{ matrix.toolchain }}
          args: --target ${{ matrix.arch }} -- -D warnings
